// pages/signin.tsx
import React, { useCallback, useState } from "react";
import Link from "next/link";
import TextInput from "../src/components/forms/TextInput";
import NotificationBox from "../src/components/NotificationBox";
import { useMutation } from "@apollo/client";
import { TOKEN_AUTH_REQUEST } from "../src/api/auth/mutations";
import Form from "../src/components/forms/Form";
import useCookie from "react-use-cookie";
import { useRouter } from "next/router";
import SubmitButton from "../src/components/forms/SubmitButton";
import AuthLayout from "../src/components/layouts/AuthLayout";
import useFormStatus from "../src/hooks/useFormStatus";

const SignInPage: React.FC = () => {
  const router = useRouter();
  const [username, setUsername] = useState<string>("");
  const [password, setPassword] = useState<string>("");

  const { setError, status } = useFormStatus();
  const [requestToken, { loading }] = useMutation(TOKEN_AUTH_REQUEST);

  const [_authToken, setAuthToken] = useCookie("authToken");
  const [_refreshToken, setRefreshToken] = useCookie("refreshToken");

  const signIn = useCallback(() => {
    requestToken({ variables: { username, password } })
      .then((res) => {
        const response = res.data?.tokenAuth;
        if (response) {
          setAuthToken(response.token);
          setRefreshToken(response.refreshToken);
          router.push("/");
        }
        if (res.errors) {
          setError(res.errors[0].message);
        }
      })
      .catch((err) => setError(err.message));
  }, [
    password,
    username,
    requestToken,
    router,
    setAuthToken,
    setError,
    setRefreshToken,
  ]);

  return (
    <AuthLayout headerText="Welcome Back!">
      <Form onSubmit={signIn}>
        <TextInput
          required
          id="username"
          label="Username"
          value={username}
          onInput={setUsername}
          className="form-input w-full"
          type="username"
        />
        <TextInput
          required
          label="Password"
          id="password"
          value={password}
          onInput={setPassword}
          className="form-input w-full"
          type="password"
          autoComplete="on"
        />
        <div className="flex items-center justify-between mt-6">
          <div className="mr-1">
            <Link
              className="text-sm underline hover:no-underline"
              href="/reset-password"
            >
              Forgot Password?
            </Link>
          </div>
          <div className="flex justify-end mt-6">
            <SubmitButton loading={loading} buttonText="Sign in" />
          </div>
        </div>
      </Form>
      <div className="pt-5 mt-6 border-t border-slate-200">
        <div className="text-sm">
          Don’t have an account?{" "}
          <Link
            className="font-medium text-indigo-500 hover:text-indigo-600"
            href="/signup"
          >
            Sign Up
          </Link>
        </div>
        <NotificationBox notification={status} />
      </div>
    </AuthLayout>
  );
};

export default SignInPage;

// src/pages/Signin.vue
<template>
  <main class="bg-white">

    <div class="relative flex">

      <!-- Content -->
      <div class="w-full md:w-1/2">
        <div class="min-h-screen h-full flex flex-col after:flex-1">

          <div class="flex-1">
            <div class="flex items-center justify-between h-16 px-4 sm:px-6 lg:px-8">
              <!-- Logo -->
              <router-link class="block" to="/">
                <svg width="32" height="32" viewBox="0 0 32 32">
                  <defs>
                    <linearGradient x1="28.538%" y1="20.229%" x2="100%" y2="108.156%" id="logo-a">
                      <stop stop-color="#A5B4FC" stop-opacity="0" offset="0%" />
                      <stop stop-color="#A5B4FC" offset="100%" />
                    </linearGradient>
                    <linearGradient x1="88.638%" y1="29.267%" x2="22.42%" y2="100%" id="logo-b">
                      <stop stop-color="#38BDF8" stop-opacity="0" offset="0%" />
                      <stop stop-color="#38BDF8" offset="100%" />
                    </linearGradient>
                  </defs>
                  <rect fill="#6366F1" width="32" height="32" rx="16" />
                  <path d="M18.277.16C26.035 1.267 32 7.938 32 16c0 8.837-7.163 16-16 16a15.937 15.937 0 01-10.426-3.863L18.277.161z" fill="#4F46E5" />
                  <path d="M7.404 2.503l18.339 26.19A15.93 15.93 0 0116 32C7.163 32 0 24.837 0 16 0 10.327 2.952 5.344 7.404 2.503z" fill="url(#logo-a)" />
                  <path d="M2.223 24.14L29.777 7.86A15.926 15.926 0 0132 16c0 8.837-7.163 16-16 16-5.864 0-10.991-3.154-13.777-7.86z" fill="url(#logo-b)" />
                </svg>
              </router-link>
            </div>
          </div>          

          <div class="max-w-sm mx-auto px-4 py-8">
            <h1 class="text-3xl text-slate-800 font-bold mb-6">Welcome back! ✨</h1>
            <!-- Form -->
            <form @submit.prevent="signIn">
              <div class="space-y-4">
                <div>
                  <label class="block text-sm font-medium mb-1" for="username">Username</label>
                  <input required id="username" v-model="username" class="form-input w-full" type="username" />
                </div>
                <div>
                  <label class="block text-sm font-medium mb-1" for="password">Password</label>
                  <input required id="password" v-model="password" class="form-input w-full" type="password" autoComplete="on" />
                </div>
              </div>
              <div class="flex items-center justify-between mt-6">
                <div class="mr-1">
                  <router-link class="text-sm underline hover:no-underline" to="/reset-password">Forgot Password?</router-link>
                </div>
                <button class="btn bg-indigo-500 hover:bg-indigo-600 text-white ml-3" to="/">Sign In</button>
              </div>
            </form>
            <!-- Footer -->
            <div class="pt-5 mt-6 border-t border-slate-200">
              <div class="text-sm">
                Don’t have an account? <router-link class="font-medium text-indigo-500 hover:text-indigo-600" to="/signup">Sign Up</router-link>
              </div>
              <!-- Notification Msg -->
              <NotificationBox v-if="notification" :message="notification" :is-error="error" />
            </div>
          </div>

        </div>
      </div>

      <!-- Image -->
      <div class="hidden md:block absolute top-0 bottom-0 right-0 md:w-1/2" aria-hidden="true">
        <img class="object-cover object-center w-full h-full" src="../images/auth-image.jpg" width="760" height="1024" alt="Authentication" />
        <img class="absolute top-1/4 left-0 -translate-x-1/2 ml-8 hidden lg:block" src="../images/auth-decoration.png" width="218" height="224" alt="Authentication decoration" />
      </div>

    </div>

  </main>
</template>

<script>
import NotificationBox from '../partials/utils/NotificationBox.vue'
import { AUTH_REQUEST } from '../store/actions/auth'


export default {
  name: 'Signin',
  components: {
    NotificationBox,
  },
  data() {
    return {
      username: '',
      password: '',
      notification: null,
      error: null,
    }
  },
  methods: {
    signIn() {
      const { password, username } = this
      this.$store.dispatch(AUTH_REQUEST, { password, username }).then(resp => {
        if (this.$store.state.auth.error) {
          this.notification = this.$store.state.auth.error
          this.error = true
        } else {
          this.error = false
          this.$router.push('/')
        }
      })
    },
  }
}
</script>
